[package]
name = "aca-graph"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
aca-types = { workspace = true }
aca-util = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
