"""Held-out generic cases for the closed default tool-intent specialist."""

CASES = [
    ("current_time", "Could you tell me what time it is right now?"),
    ("current_time", "What is today's date?"),
    ("current_time", "Please check the current local time."),
    ("current_time", "Which day of the week is it?"),
    ("current_time", "Read the clock for me."),
    ("current_time", "I need the current date and time."),
    ("current_time", "What time do you have?"),
    ("current_time", "Tell me the date today."),
    ("current_time", "Can you report the present time?"),
    ("current_time", "Check what the calendar date is now."),
    ("self_status", "What are you thinking about at the moment?"),
    ("self_status", "How are you feeling right now?"),
    ("self_status", "What currently has your attention?"),
    ("self_status", "Describe what is in your working memory."),
    ("self_status", "Are you cognitively busy?"),
    ("self_status", "Give me a short report on your mental state."),
    ("self_status", "What is going on inside your cognition?"),
    ("self_status", "Tell me your current internal status."),
    ("self_status", "Where is your focus right now?"),
    ("self_status", "Summarize your present cognitive condition."),
    ("abstraction_status", "What pattern have you formed across those memories?"),
    ("abstraction_status", "Show me your current provisional abstraction."),
    ("abstraction_status", "What generalization are you developing?"),
    ("abstraction_status", "Report the latest cross-memory pattern."),
    ("abstraction_status", "What hypothesis did synthesis produce?"),
    ("abstraction_status", "Describe your current abstraction."),
    ("abstraction_status", "Have you inferred a common structure yet?"),
    ("abstraction_status", "Tell me the pattern your memories suggest."),
    ("abstraction_status", "What conceptual summary have you formed?"),
    ("abstraction_status", "Read back the latest synthesized generalization."),
    ("none", "Time flies when a project is interesting."),
    ("none", "I updated the project status yesterday."),
    ("none", "The wallpaper has a repeating pattern."),
    ("none", "Working memory is an important topic in cognitive science."),
    ("none", "The current date field belongs in the report schema."),
    ("none", "Your architecture includes attention and cognition."),
    ("none", "We should discuss abstraction in the next design review."),
    ("none", "That clock has a beautiful face."),
    ("none", "The status page uses a blue background."),
    ("none", "Pattern matching can be implemented without a tool call."),
]
